### ISSUE TITLE
[Bug]: contentType header is missing in response headers

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#3643]
### Describe the bug

content type header is missng in response headers. And I didn't see anything mentioned this kind of removal in the release notes of 0.57.0 

here's what the route.response shows in version 0.56.0

![image](https://github.com/microsoft/typespec/assets/55688292/2d458d18-5add-418f-8b9f-b9e4a72b49ee)

here's what the route.response shows in version 0.57.0

![image](https://github.com/microsoft/typespec/assets/55688292/8ab83662-f74a-4611-ac2b-7822e3e356ab)

From what TypeGraph shows, the returnType of operation getSchemaById has this contentType header, but it's missing from getHttpOperation.

### Reproduction

[Playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGnZlcnNpb25pbmfEIA0KdXNpbmcgVHlwZVNwZWMuSHR0cDvRFlJlc3TSFlbJS8VKQHVzZUF1dGgoQmVhcmVyxAspDQpAc2VydmljZSh7DQogIHRpdGxlOiAiQXp1cmUgU2NoZW1hIFJlZ2lzdHJ5IiwNCn0pxEsvLyAgR0VUIOQA4XM6Ly97bmFtZXNwYWNlTmFtZX0ux1RidXMud2luZG93cy5uZXQvJHPFUUdyb3Vwcz9hcGkt5wDuPXthcGnnAK9931%2FfX8hfyA5zL3tpZH3fbd9t321wcy97Z8QIxTEvyXjESX3oAdFzL%2F8AhP8AhP8AhP8AhMZqcy97xhnIev8Ak1BPU%2F8AlP8AlPwAlDpnZXQtaWT%2FAINQVf8Agv8AgvsAgtt65QMVZXIo5AMTIntmdWxseVF1YWxpZmllZMRL5QCFfeQDECAgIlRo8QMqIOcAmyBlbmRwb2ludC7GLOUDZCAgQGRvYyjfOMY4LCBmb3IgZXhhbXBsZSAnbXkt6QEE9wD%2FJy4iKcZm9wC3OiB1cmzlAI59DQrkBAHnAQNlZChTxlJB6QELc8Qg5QCt5gCp6ACoQ2xpZW50IGlzIGEgY8YM5ACocsUfZXLkBIZhbmQgcmV0cmlldsQP5wF7IGZyb20gdGhlIPUEYugBAOUAxOkA6sYsLu4Ag%2BYE0%2BUAnFJlcHJlc2VudHPFWtBUQVBJIOcA5CB0byB1c2XnAK1xdWVzdHPFbGVudW0g8gD%2F5gGxxmb2ALEyMDIzLTA3LTAxIMc1LiBUaGlz5AEc5ACNZGVmYXVsdOgAgcVtICBWxDdfMDdfMDE6ICLKROUFYuoA2U9iamVjdCByZWNlaXZlZOoBPeYBaXJ5IGNvbnRhaeQF4%2BcBYiBpZGVudOQB8nLmANpAcmVzb3VyY2UoIvYFIMQlbW9kZWznANxJZOcA9mtleSgiaWTEIOgBBMYiIElEIHRoYXQgdW5pcXVlbHnKdeQCEcZYIGlu7gCr6gK5x1J2aXNpYmlsaXR5KCJyZWHHaWlkOiBzdOQCQzvtAQxIZWFkZXJz5QG7bWV0YWRhdGEgb2bJcMVW7ADIyDHrAcNVUkwgbG9jYXTkAgtvZsc6LOoAv2QgYnnHFiDlBDgsyA7kAL4s5QLV7gHKQGjFZygiTMdYxhfIZusAzOoAh1JlZmVyZW5jZXMg5AfzaWZpY8hnaW77ATHIa%2BYA4C1J5wEyxjtJ7AE4%2FwDz%2BADzSUTZay3uAODIdMgW1XzsAOjrAVTXZOUCly3kBKfMY8UWxBXfYshi5AE112HQW9lW5wPJ5AEv5gLCdHVybmVk7AJp0l7HNcxhxxM6IGludDMy7gLPQ29udOQFN8dk9wLEyCbmAsRib2R56wOM5QC5IHLoBP3mAeMoVVRGLTgp01gg5QQtZW50OiBieXRlc%2B4AkOQGjccgIOQKjOUDaGdpdmVuyEQgRWFjaMcNxiNoYXMgYW4gYXNzb2NpYXRlZMhCLcQf%2BADN5Aqf7AOV33ryAXHHSC3ESe0A2cQROtJtVmFsdeoA73Vu5AEn1yXmAJhhdnJvOiAiYXBwbGnmAt8vanNvbjvkBp5pYWxpesUUPUF2cm%2FmB9fEHt8xxDHEFMYxY3VzdG9tOiAidGV4dC9wbGFpbjsgY2hhcnNldD11dGYtOMYocHJvdG9idWbIKnZuZC5tcy7IF%2BkGL2ludGVyZuQHK%2BYA2U9wZXLFdOgE%2F3N1bW1hcnkoIkdldCBh6Qep6QLV5AQFaXRz5wXS5AXhcugDW%2BgBf%2BUBrUdldOQF499A5ARJIPcH4md1YXJhbnRlZeQHIGF0xGtpyTh3aXRoaW4g5gPH5gT8IOkAzCByZXNwb25zZeYCJ2lzIGJhc2VkIG9u7gFo6gTn6AfkZWToAMVyb3V0ZSgi%2FAwrxypnZXTECGdldOYAwkJ5SWQoQHBhdGjrBqMpOiBPa1LoAJcmxDEg7wZ%2FzRXoA9DUFeQChuYCpQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lirenhe** [comment]
For languages that would include headers in the response model like JS & GO, this is likely to be a breaking change for the SDK.
@allenjzhang, @markcowl, could you help to confirm whether this behavior is by design? This would impact our emitters to move to TypeSpec 0.57.
cc @lmazuel for awareness.

**Comment by weidongxu-microsoft** [comment]
No impact for Java emitter, so far. The response in Java is `Response<T>` where headers is a dict (so it is runtime).

**Comment by allenjzhang** [comment]
This is by design.  Response `content-type` is express via `Produce` in [Swagger ](https://swagger.io/docs/specification/2-0/describing-responses/) and `content` in [OAS 3.0](https://swagger.io/docs/specification/describing-responses/). See respective linked specs.

This is correctly expressed in [swagger playground](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGnZlcnNpb25pbmfEIA0KdXNpbmcgVHlwZVNwZWMuSHR0cDvRFlJlc3TSFlbJS8VKQHVzZUF1dGgoQmVhcmVyxAspDQpAc2VydmljZSh7DQogIHRpdGxlOiAiQXp1cmUgU2NoZW1hIFJlZ2lzdHJ5IiwNCn0pxEsvLyAgR0VUIOQA4XM6Ly97bmFtZXNwYWNlTmFtZX0ux1RidXMud2luZG93cy5uZXQvJHPFUUdyb3Vwcz9hcGkt5wDuPXthcGnnAK9931%2FfX8hfyA5zL3tpZH3fbd9t321wcy97Z8QIxTEvyXjESX3oAdFzL%2F8AhP8AhP8AhP8AhMZqcy97xhnIev8Ak1BPU%2F8AlP8AlPwAlDpnZXQtaWT%2FAINQVf8Agv8AgvsAgtt65QMVZXIo5AMTIntmdWxseVF1YWxpZmllZMRL5QCFfeQDECAgIlRo8QMqIOcAmyBlbmRwb2ludC7GLOUDZCAgQGRvYyjfOMY4LCBmb3IgZXhhbXBsZSAnbXkt6QEE9wD%2FJy4iKcZm9wC3OiB1cmzlAI59DQrkBAHnAQNlZChTxlJB6QELc8Qg5QCt5gCp6ACoQ2xpZW50IGlzIGEgY8YM5ACocsUfZXLkBIZhbmQgcmV0cmlldsQP5wF7IGZyb20gdGhlIPUEYugBAOUAxOkA6sYsLu4Ag%2BYE0%2BUAnFJlcHJlc2VudHPFWtBUQVBJIOcA5CB0byB1c2XnAK1xdWVzdHPFbGVudW0g8gD%2F5gGxxmb2ALEyMDIzLTA3LTAxIMc1LiBUaGlz5AEc5ACNZGVmYXVsdOgAgcVtICBWxDdfMDdfMDE6ICLKROUFYuoA2U9iamVjdCByZWNlaXZlZOoBPeYBaXJ5IGNvbnRhaeQF4%2BcBYiBpZGVudOQB8nLmANpAcmVzb3VyY2UoIvYFIMQlbW9kZWznANxJZOcA9mtleSgiaWTEIOgBBMYiIElEIHRoYXQgdW5pcXVlbHnKdeQCEcZYIGlu7gCr6gK5x1J2aXNpYmlsaXR5KCJyZWHHaWlkOiBzdOQCQzvtAQxIZWFkZXJz5QG7bWV0YWRhdGEgb2bJcMVW7ADIyDHrAcNVUkwgbG9jYXTkAgtvZsc6LOoAv2QgYnnHFiDlBDgsyA7kAL4s5QLV7gHKQGjFZygiTMdYxhfIZusAzOoAh1JlZmVyZW5jZXMg5AfzaWZpY8hnaW77ATHIa%2BYA4C1J5wEyxjtJ7AE4%2FwDz%2BADzSUTZay3uAODIdMgW1XzsAOjrAVTXZOUCly3kBKfMY8UWxBXfYshi5AE112HQW9lW5wPJ5AEv5gLCdHVybmVk7AJp0l7HNcxhxxM6IGludDMy7gLPQ29udOQFN8dk9wLEyCbmAsRib2R56wOM5QC5IHLoBP3mAeMoVVRGLTgp01gg5QQtZW50OiBieXRlc%2B4AkOQGjccgIOQKjOUDaGdpdmVuyEQgRWFjaMcNxiNoYXMgYW4gYXNzb2NpYXRlZMhCLcQf%2BADN5Aqf7AOV33ryAXHHSC3ESe0A2cQROtJtVmFsdeoA73Vu5AEn1yXmAJhhdnJvOiAiYXBwbGnmAt8vanNvbjvkBp5pYWxpesUUPUF2cm%2FmB9fEHt8xxDHEFMYxY3VzdG9tOiAidGV4dC9wbGFpbjsgY2hhcnNldD11dGYtOMYocHJvdG9idWbIKnZuZC5tcy7IF%2BkGL2ludGVyZuQHK%2BYA2U9wZXLFdOgE%2F3N1bW1hcnkoIkdldCBh6Qep6QLV5AQFaXRz5wXS5AXhcugDW%2BgBf%2BUBrUdldOQF499A5ARJIPcH4md1YXJhbnRlZeQHIGF0xGtpyTh3aXRoaW4g5gPH5gT8IOkAzCByZXNwb25zZeYCJ2lzIGJhc2VkIG9u7gFo6gTn6AfkZWToAMVyb3V0ZSgi%2FAwrxypnZXTECGdldOYAwkJ5SWQoQHBhdGjrBqMpOiBPa1LoAJcmxDEg7wZ%2FzRXoA9DUFeQChuYCpQ%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D) and [OAS3.0 playground](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TWGnZlcnNpb25pbmfEIA0KdXNpbmcgVHlwZVNwZWMuSHR0cDvRFlJlc3TSFlbJS8VKQHVzZUF1dGgoQmVhcmVyxAspDQpAc2VydmljZSh7DQogIHRpdGxlOiAiQXp1cmUgU2NoZW1hIFJlZ2lzdHJ5IiwNCn0pxEsvLyAgR0VUIOQA4XM6Ly97bmFtZXNwYWNlTmFtZX0ux1RidXMud2luZG93cy5uZXQvJHPFUUdyb3Vwcz9hcGkt5wDuPXthcGnnAK9931%2FfX8hfyA5zL3tpZH3fbd9t321wcy97Z8QIxTEvyXjESX3oAdFzL%2F8AhP8AhP8AhP8AhMZqcy97xhnIev8Ak1BPU%2F8AlP8AlPwAlDpnZXQtaWT%2FAINQVf8Agv8AgvsAgtt65QMVZXIo5AMTIntmdWxseVF1YWxpZmllZMRL5QCFfeQDECAgIlRo8QMqIOcAmyBlbmRwb2ludC7GLOUDZCAgQGRvYyjfOMY4LCBmb3IgZXhhbXBsZSAnbXkt6QEE9wD%2FJy4iKcZm9wC3OiB1cmzlAI59DQrkBAHnAQNlZChTxlJB6QELc8Qg5QCt5gCp6ACoQ2xpZW50IGlzIGEgY8YM5ACocsUfZXLkBIZhbmQgcmV0cmlldsQP5wF7IGZyb20gdGhlIPUEYugBAOUAxOkA6sYsLu4Ag%2BYE0%2BUAnFJlcHJlc2VudHPFWtBUQVBJIOcA5CB0byB1c2XnAK1xdWVzdHPFbGVudW0g8gD%2F5gGxxmb2ALEyMDIzLTA3LTAxIMc1LiBUaGlz5AEc5ACNZGVmYXVsdOgAgcVtICBWxDdfMDdfMDE6ICLKROUFYuoA2U9iamVjdCByZWNlaXZlZOoBPeYBaXJ5IGNvbnRhaeQF4%2BcBYiBpZGVudOQB8nLmANpAcmVzb3VyY2UoIvYFIMQlbW9kZWznANxJZOcA9mtleSgiaWTEIOgBBMYiIElEIHRoYXQgdW5pcXVlbHnKdeQCEcZYIGlu7gCr6gK5x1J2aXNpYmlsaXR5KCJyZWHHaWlkOiBzdOQCQzvtAQxIZWFkZXJz5QG7bWV0YWRhdGEgb2bJcMVW7ADIyDHrAcNVUkwgbG9jYXTkAgtvZsc6LOoAv2QgYnnHFiDlBDgsyA7kAL4s5QLV7gHKQGjFZygiTMdYxhfIZusAzOoAh1JlZmVyZW5jZXMg5AfzaWZpY8hnaW77ATHIa%2BYA4C1J5wEyxjtJ7AE4%2FwDz%2BADzSUTZay3uAODIdMgW1XzsAOjrAVTXZOUCly3kBKfMY8UWxBXfYshi5AE112HQW9lW5wPJ5AEv5gLCdHVybmVk7AJp0l7HNcxhxxM6IGludDMyx2PkBtXrBgHkA8HkBT%2FkCgDlAtxnaXZlbs5rLy%2FKbkPGMC3kCeXJHsdFxBQxOucC%2F8cpxBRWYWx1ZXPuA0%2FHH%2BgA5PcDRMgm5gNEYm9keesEDOUBOSBy6AV95gJjKFVURi04KdNYIOgApzogYnl08ACQ%2FwEMbWEuIEVhY2jHDcYjaGFzIGFuIGFzc29jaWF0ZWTIQi3EH%2FgAzeQBEuwEFd968gHx8gGD6wGA%2FwF%2FDQp1buQBJ9cl5gCYYXZybzogImFwcGxp5gNfL2pzb2475AceaWFsaXrFFD1BdnJv5ghXxB7fMcQxxBTGMWN1c3RvbTogInRleHQvcGxhaW47IGNoYXJzZXQ9dXRmLTjGKHByb3RvYnVmyCp2bmQubXMuyBfpBq9pbnRlcmbkB6vmANlPcGVyxXToBX9zdW1tYXJ5KCJHZXQgYekIKekDVeQEhWl0c%2BcGUuQGYXLoA9voAX%2FlAa1HZXTkBmPfQOQEySD3CGJndWFyYW50ZWXkB6BhdMRrack4d2l0aGluIOYER%2BYFfCDpAMwgcmVzcG9uc2XmAidpcyBiYXNlZCBvbu4BaOoFZ%2BgIZGVk6ADFcm91dGUoIvwMq8cqZ2V0xAhnZXTmAMJCeUlkKEBwYXRo6wcjKTogT2tS6ACXJsQxIO8G%2F80V6APQ1BXkAobmAqU%3D&e=%40typespec%2Fopenapi3&options=%7B%7D).

**Comment by allenjzhang** [comment]
Sorry, the above was commented as for the autorest/OAS3 emitter and not exactly you are referring to. For the getHttpOperation function result , there was some refactoring around [httpProperty ](https://github.com/microsoft/typespec/blob/831e0c8e0921ca5ab9c813fc74ece737b484193b/packages/http/src/http-property.ts#L124) that explicitly separated contentType into a new contentType HttpProperty.  This actually fixed a [casing bug originally existed](https://github.com/timotheeguerin/typespec/blob/da99aa955b497c34cd6deb8f873fecd0d583c85b/packages/http/src/responses.ts#L223). 

Now that is fixed, please switch the logic to access the `body.contentTypes`. If you still want it as part of `headers`, additional logic will be needed to filter them out in autorest and openapi3 emitters, as I mentioned above. So that would be far less ideal.

**Comment by bterlson** [comment]
Worth noting explicitly that the presence of "Content-Type" in the headers list is a bug, if it were called "content-type" instead it would have been excluded properly, so the previous code relying on this was still incorrect. [This playground](https://typespec.io/playground?version=0.56.x&c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdCI7CgpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN0OwoKaW50ZXJmxEPGYcdFIMR7QMRxQHJvdXRlKCJjdXN0b21HZXQiKSDJDCgpOsUqICAvLyBjaGFuZ2UgdGhpcyAtLXYgY2HFcmFuZCB3YXRjaCB0aGUgY29udGVudC3kAPUgaGVhZGVyIGFwcGVhciBpbscRc8VSQMYNKCLIM%2BQAuyIpIMQ6OiAidGV4dC9wbGFpbngiLMYxYm9keSDEBTogc3RyaW5nCiAgfQp9Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D) shows the bug that existed previously.

FWIW I definitely prefer to just fix the bug and change how emitters are accessing content type. Adding the content type headers to the header collection seems likely to have a lot of downstream impact beyond our own openapi3 and autorest emitters.

**Comment by qiaozha** [comment]
Thanks @allenjzhang and @bterlson  for the investigation and suggestions, I will use body.contentTypeProperty to make it work.
