### ISSUE TITLE
Can't emit Python into a specific output directory

### ISSUE THREAD

**Issue by mccoyp** [microsoft/typespec#5605]
### Context
I'm in the process of migrating a brownfield service (Key Vault) to TypeSpec (https://github.com/Azure/azure-rest-api-specs/pull/28708) and have been struggling to emit Python code that matches our original SDK structure. In `azure-keyvault-certificates` we keep all generated code in a [`_generated`](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_generated) module; we'd like to emit from TSP into the same directory.

I'm able to match our original SDK structure by placing `tsp-location.yaml` in `_generated/`, emitting with `tsp-client update`, and manually deleting everything that's emitted apart from source code. However, this isn't an ideal solution:

1. This manual work is tedious and can't be easily done with automation.
2. The modified SDK structure doesn't match the emitter's assumptions. For example, generated model references point to `azure.keyvault.certificates.models`, when the new location is `azure.keyvault.certificates._generated.models`. This would break references, e.g. in docs.
3. Packaging info we want to keep, like `setup.py`, isn't automatically updated. We'd like to emit from the root of the package so that packaging information gets correctly updated.

### Attempted solutions
I've tried a number of configurations in `tspconfig.yaml` to achieve this, which haven't worked:

- Attempted values for `"output-path"`:
  - `"./azure/keyvault/certificates/_generated"`
  - `"azure-keyvault-certificates/azure/keyvault/certificates/_generated"`
  - `"azure.keyvault.certificates._generated"`
- Attempted values for `"emitter-output-dir"`:
  - `"./azure/keyvault/certificates/_generated"`
  - `"azure-keyvault-certificates/azure/keyvault/certificates/_generated"`
  - `"azure.keyvault.certificates._generated"`
- Attempted values for `"namespace"`:
  - `"azure.keyvault.certificates._generated"`

In all of these attempts, running `tsp-client update` from the root of `azure-keyvault-certificates` emits the code into the package root, instead of into `_generated/`. Here are the files that are changed (moving `tsp-location.yaml` to the package root was done manually; everything else is emitted):

![Image](https://github.com/user-attachments/assets/efa51384-0bb9-432d-b933-40361dba86c6)

#### Additional information
In these attempts I've been using the `--local-spec-repo` option, which may or may not be relevant. The `tsp-client` output consistently indicates that the output directory is the package root:

```bash
mcpatino@DESKTOP-DPKUD1A:~/azure-sdk-for-python/sdk/keyvault/azure-keyvault-certificates$ tsp-client update --local-spec-repo ../../../../azure-rest-api-specs/specification/keyvault/Security.KeyVault.Certificates/
Using output directory '/home/mcpatino/azure-sdk-for-python/sdk/keyvault/azure-keyvault-certificates'
...
```

**Comment by msyyc** [comment]
Let me make an investigation.

**Comment by msyyc** [comment]
Update: since user only need function code instead of whole package, python emitter need new feature to support that.

**Comment by iscai-msft** [comment]
tldr: add `generation-subdir`. Here are the notes from our discussion

# North Star

sdk/keyvault/azure-kevault-certificates
    azure
     -> keyvault
       -> certificates
         -> _version.py
         -> _generated
            -> _client.py
    -> setup.py # needs to make sure that it packages everything in azure/keyvault/certificates, including _generated

- output root -> emitter-output-dir
- packaging root ->
- generation root -> generation-subfolder?

package-name: azure-keyvault-certificates
namespace: azure.keyvault.certificates
generation-subdir: /_generated

tsp-client uses `service-dir` and `package-dir`. `package-dir` is where the setup.py is, so in this case `azure-keyvault-certificates`.


- These are usually the same / inferred, here we're trying to customize generation root, while still keeping the packaging root the same, and including everything within it.

**Comment by maorleger** [comment]
👋 this looks very similar to what @dgetu was working on in the TypeScript emitter - maybe it makes sense to come up with a language / flag that is consistent across languages? @joheredi FYI

**Comment by iscai-msft** [comment]
thanks for the heads up @maorleger. Let me make a note to talk about this in our group sync

**Comment by mccoyp** [comment]
Update: this is now almost completely working! I modified our `tspconfig.yaml` to include `"namespace": "azure.keyvault.certificates._generated"` -- after doing so, running `tsp-client update` from the package root in the SDK repo correctly emitted code into a `generated` folder, left handwritten code outside that folder untouched (aside from applying linting rules/`black`), and updated the library's `setup.py`. Model references in generated code docstrings correctly point to the `azure.keyvault.x.generated` namespace.

There are only two points of refinement that would satisfy our original ask:

1. The output folder is `generated` instead of `_generated`, so the leading underscore isn't being preserved. We'd like to keep the underscore since our generated code is supposed to be private.
2. Though we do want `setup.py` to get updated, the current output gets rid of additional dependencies that were added from handwritten code. For example, in `azure-keyvault-keys` we have a [dependency on `cryptography`](https://github.com/Azure/azure-sdk-for-python/blob/2f95178ca1b5e0159f18c6903001ad645e691f2c/sdk/keyvault/azure-keyvault-keys/setup.py#L72). Since the generated code doesn't incur that dependency on its own, the requirement is discarded while updating `setup.py`. We'd like the emitter to update the file, but preserve any additional dependencies that were present.
    1. In this case, identifying that an additional dependency in `install_requires` should probably help to get the emitting right. In cases where handwritten code might require a newer dependency than the generated code -- e.g. if Keys required a higher lower bound of `azure-core` -- we'd probably want the emitter to defer to the existing requirement in that case as well.

**Comment by msyyc** [comment]
Hi @mccoyp 
1. It is already fixed in latest emitter and please have a try again.
2. I afraid it is a little hard since emitter doesn't support partially update SDK files, including `setup.py`.

**Comment by iscai-msft** [comment]
So for #2 I've gone ahead and added additional parameterization to the `setup.py` template and have talked to @mccoyp about this offline. This way, they can use the package-dir flag and specify their own setup.py template while still getting automatic versioning updating

**Comment by iscai-msft** [comment]
I'm going to close this issue, since I think the main issue is resolved, for the other issues that we run into, we can open additional issues. Thanks everyone!
