### ISSUE TITLE
[Bug]: Enum value not assignable to model type when using versions with 0.65.0

### ISSUE THREAD

**Issue by ssams** [microsoft/typespec#5999]
### Describe the bug

I've got a model which represents a list consisting of either enum values or some additional option (see playground example). I'm using examples to describe the model. Additionally the service is versioned.

Providing example values for this array/model worked fine with typespec _0.64.0_, but after upgrading to _0.65.0_ (or 0.65.1 for compiler) I receive an error "not assignable to type". It seems to be related to the versioning library, as soon as I remove the `@versioned` decorator it would start working again.

### Reproduction

[Playground Link](https://typespec.io/playground/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZdmVyc2lvbmluZyI7Cgp1c2luZyBIdHRwO8cMVskgOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiRGVtbyBBUEkiLAp9KQpAx1FlZCjHO3MpIC8vIHJlbW92xFF0aGlzIGxpbmUgbWFrZXMgaXQgY29tcGlsZSBhZ2FpbgpuYW1lc3BhY2UgxFo7CgplbnVt6ACIcyDEe3YxLAp9xxlGZWF0dXJlTmFtZcUcYSwKICBixSBAZXhhbXBsZSgjWyIqIl3lAIh3b3Jrc8way0AuYcYkZXJyb3IgaW4gMC42NS4wLMU1ZWTHEjQuMAptb2RlbMh7cyBpcyAoy0ggfCAiKiIpW107Cgo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

```ts
import "@typespec/http";
import "@typespec/versioning";

using Http;
using Versioning;

@service({
  title: "Demo API",
})
@versioned(Versions) // removing this line makes it compile again
namespace Demo;

enum Versions {
  v1,
}

enum FeatureName {
  a,
  b,
}

@example(#["*"]) // works
@example(#[FeatureName.a]) // error in 0.65.0, worked in 0.64.0
model Features is (FeatureName | "*")[];
```

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
fixed in compiler 0.65.2, should publish soon

**Comment by ssams** [comment]
> fixed in compiler 0.65.2, should publish soon

thanks for the quick handling of this. could it be that it missed the 0.65.2 release though, commit bc95c93bd42c997c723d400e62ffde35c0856cc9 and its contents seem not to be part of the respective tag (https://github.com/microsoft/typespec/compare/%40typespec/compiler%400.65.1...%40typespec/compiler%400.65.2)? (also I still see the same error when using the published version, hence I started looking at the commits/tags)

**Comment by timotheeguerin** [comment]
hhm weird, this was done on the release/ branch which does have the other commit before https://github.com/microsoft/typespec/commits/release/feb-2025/ maybe I didn't fix as expected

**Comment by timotheeguerin** [comment]
@ssams actually this is is fixed for me(seems like we have a separate issue https://github.com/microsoft/typespec/issues/6017 )

<img width="680" alt="Image" src="https://github.com/user-attachments/assets/1ca57b90-17a9-4fb5-b8f3-d079c42db7ad" />

**Comment by ssams** [comment]
you're right, the example I posted is indeed fixed, sorry.

my statement that I still see the error was based on my actual full project, where I really still observe problem, however there's a slight difference to the reproduction:

```
@opExample(#{parameters: #{test: #["*"]}})
@opExample(#{parameters: #{test: #[FeatureName.a, FeatureName.b]}})
op features(test: Features): void;
```

-> `opExample` is still broken, whilst `example` which I originally reported now works. when creating the minimal reproduction I saw that it creates the error even without the operation directly on the model, and just assumed both would be equally affected and any fix would apply to both.

should I create a new / separate issue for `opExample`?

**Comment by timotheeguerin** [comment]
Of course…

**Comment by timotheeguerin** [comment]
Alright now it should be fixed in 0.65.3
